### ISSUE TITLE
`undefined method '<<' for nil:NilClass` in `Converters::CSV.masscan_file_to_csv`

### ISSUE THREAD

**Issue by AI-Mozi** [ronin-rb/ronin-masscan#14]
In `Converters::CSV.convert` `output` argument will be set to `nil` if we wont specify it.
Then it will call `masscan_file_to_csv(mascan_file, nil`) so `masscan_file_to_csv`'s `output` argument default value won't be applied and `<<` will be called on Nil.

I think we should change default value in `.convert` from `nil` to `String.new`

**Comment by postmodern** [comment]
You are correct. It should either be changed to `masscan_file_to_csv(masscan_file,*output)` to cause the `nil` value to be omitted, or change `output=nil` to `output=String.new` to match `masscan_file_to_csv`.

**Comment by postmodern** [comment]
Looking at `ronin-nmap/lib/ronin/nmap/converters/csv.rb`, it uses `output=String.new`, so I vote for that option to remain consistent.

**Comment by postmodern** [comment]
Fixed by #15.
